spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HvsM?useSSL=false&allowPublicKeyRetrieval=true
    username: francesco
    password: Password.2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true